linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
      - '^panic$'
  importas:
    no-unaliased: true
    alias:
      - pkg:  buf.build/gen/go/bufbuild/knit/protocolbuffers/go/buf/knit/gateway/v1alpha1
        alias: gatewayv1alpha1
      - pkg: github.com/bufbuild/connect-go
        alias: connect
      - pkg: github.com/bufbuild/connect-grpcreflect-go
        alias: grpcreflect
      - pkg: github.com/bufbuild/knit-go
        alias: knit
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
linters:
  enable-all: true
  disable:
    - cyclop            # covered by gocyclo
    - depguard          # draconian in unhelpful ways
    - exhaustruct       # not useful for this repo (we want to rely on zero values for fields)
    - funlen            # rely on code review to limit function length
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - mnd               # some unnamed constants are okay
    - nlreturn          # generous whitespace violates house style
    - nonamedreturns    # named returns are fine, it's *bare* returns that are not
    - protogetter       # too many false positives
    - tenv              # deprecated in golangci v1.64.0
    - testpackage       # internal tests are fine
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
issues:
  exclude-dirs-use-default: false
  exclude:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - "do not define dynamic errors.*"
    # These are noisy with false positives.
    - "G115: integer overflow conversion"
  exclude-rules:
    - path: cmd/.*/main\.go
      linters:
        - forbidigo # log.Fatal used in standalone main functions
    - path: internal/app/knitgateway/(config|cache)\.go
      linters:
        - tagliatelle # Buf conventions for yaml varies from common practices
