project_name: knit-go
builds:
  - id: knitgateway
    binary: knitgateway
    main: ./cmd/knitgateway
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    rlcp: true
    # Follows same naming conventions as release artifacts for bufbuild/buf
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ title .Os }}-{{ if and (eq .Os "linux") (eq .Arch "arm64")}}aarch64{{ else if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    files:
      - LICENSE
      - knitgateway.example.yaml
